export const REQUEST_GIFS = 'REQUEST_GIFS';
export const REQUEST_RANDOM_GIF = 'REQUEST_RANDOM_GIF';
export const REQUEST_GIF = 'REQUEST_GIF';
export const REQUEST_TRENDING_GIFS = 'REQUEST_TRENDING_GIFS'
export const STORE_TERMS = 'SAVE_TERMS';
export const DISPLAY_TERM = 'DISPLAY_TERM';